archy export --flowName "RJV_Menir" --flowType "inboundemail" --outputDir ./flows --exportType yaml --force --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV Default In-Queue Email" --flowType "inqueueemail" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV Callback Direct Table" --flowType "commonmodule" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV Voicemail" --flowType "commonmodule" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV LastAgentRouting" --flowType "commonmodule" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV SetLanguage" --flowType "commonmodule" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV_MenhirVoiceSurvey_FR" --flowType "voicesurvey" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV Customer Journey" --flowType "commonmodule" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV_TransferToFlowExample" --flowType "inboundcall" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV_MenhirVoiceSurvey_EN" --flowType "voicesurvey" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV Menhir Direct Tables" --flowType "inboundcall" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV_MenhirVoiceSurvey_DE" --flowType "voicesurvey" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV PlayPrompt DirectTable" --flowType "commonmodule" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV Menhir In-Queue New" --flowType "inqueuecall" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie
archy export --flowName "RJV_MenhirVoiceSurvey_NL" --flowType "voicesurvey" --force --outputDir ./flows --exportType yaml --clientId $GENESYSCLOUD_OAUTHCLIENT_ID --clientSecret $GENESYSCLOUD_OAUTHCLIENT_SECRET --location mypurecloud.ie