// This file has been autogenerated. The following properties could not be retrieved from the API or would not make sense in a different org e.g. Edge IDs
// The variables contained in this file have been given default values and should be edited as necessary

genesyscloud_integration_credential_Integration-834b4733-06e6-41cf-994f-db5825a48740_fields = null
genesyscloud_flow_COMMONMODULE_RJV_Callback_Direct_Table_filepath = ""
genesyscloud_flow_COMMONMODULE_RJV_SetLanguage_filepath = ""
genesyscloud_flow_INBOUNDCALL_RJV_Menhir_Direct_Tables_filepath = ""
genesyscloud_flow_INBOUNDEMAIL_RJV_Menir_filepath = ""
genesyscloud_routing_email_domain_RJV_mypurecloud_ie_custom_smtp_server_id = ""
genesyscloud_flow_COMMONMODULE_RJV_LastAgentRouting_filepath = ""
genesyscloud_flow_INBOUNDCALL_RJV_TransferToFlowExample_filepath = ""
genesyscloud_flow_VOICESURVEY_RJV_MenhirVoiceSurvey_FR_filepath = ""
genesyscloud_flow_VOICESURVEY_RJV_MenhirVoiceSurvey_EN_filepath = ""
genesyscloud_flow_COMMONMODULE_RJV_PlayPrompt_DirectTable_filepath = ""
genesyscloud_flow_INQUEUEEMAIL_RJV_Default_In-Queue_Email_filepath = ""
genesyscloud_flow_COMMONMODULE_RJV_Voicemail_filepath = ""
genesyscloud_flow_COMMONMODULE_RJV_Customer_Journey_filepath = ""
genesyscloud_flow_VOICESURVEY_RJV_MenhirVoiceSurvey_DE_filepath = ""
genesyscloud_flow_INQUEUECALL_RJV_Menhir_In-Queue_New_filepath = ""
genesyscloud_flow_VOICESURVEY_RJV_MenhirVoiceSurvey_NL_filepath = ""