// This file has been autogenerated. The following properties could not be retrieved from the API or would not make sense in a different org e.g. Edge IDs
// The variables contained in this file have been given default values and should be edited as necessary

genesyscloud_integration_credential_Integration-834b4733-06e6-41cf-994f-db5825a48740_fields = null